// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeerkejxibtzzrussajn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlZXJrZWp4aWJ0enpydXNzYWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2NjAxNjIsImV4cCI6MjA0OTIzNjE2Mn0.wq2JckbzH7JNhfP-CRjx3ovU5QP-JUJMcKUAmqUzHZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);